version: '3,8'

services:
  ###############################
  #           bot trading       #
  ###############################
    go:
        image: go
        restart: always
        build:
            context: ./requirements/go/
            dockerfile: Dockerfile 
        environment:
            - API=${API}
            - API_SECRET=${API_SECRET}
            - API_TELEGRAM=${API_TELEGRAM}
            - URL=${URL}
        ports:
          - "30000:30000"
        networks:
             bot:

  ###############################
  #           python bot        #
  ###############################
    python:
        image: python
        restart: always
        build:
            context: ./requirements/python/
            dockerfile: Dockerfile 
        environment:
          - API_ID=${API_ID}
          - API_HASH=${API_HASH}
          - ID_CHANNEL=${ID_CHANNEL} 
          - SIGNAL_CHANNEL=${SIGNAL_CHANNEL} 
          - BOT_NAME=${BOT_NAME} 
        ports:
          - "40000:40000"
        networks:
             bot:

  ###############################
  #           mariadb           #
  ###############################
    mysql:
        image: mariadb:latest
        restart: always
        container_name: db
        environment:
          - MYSQL_DATABASE=db
          - MARIADB_USER=test 
          - MARIADB_PASSWORD=test
          - MARIADB_ROOT_PASSWORD=test
        ports:
          - "3306:3306"
        env_file: .env
        volumes:
          - ${PWD}/mariadb:/var/lib/mysql
        networks:
             bot:


# volumes:
#   mariadb-volumes:
#     driver: local
#     driver_opts:
#       device: ~/bot/mariadb/
#       type: volume
#       o: bind

networks:
     bot:
        driver: bridge
